spring.application.name=advisory-service
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.default-property-inclusion=non_null
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081